services:
  sgcc_electricity_app:
    env_file:
      - .env
    image: yanyu469/sgcc_electricity:latest # for use docker.io: arcw/sgcc_electricity:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: sgcc_electricity
    network_mode: "host"
    environment:
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=Asia/Shanghai
    restart: unless-stopped
    # volumes:
    #   - ./:/data        # if you want to read homeassistant.db, homeassistant.db is in the container at /data/
    command: python3 main.py
    init: true
